"""Phase 4 Upgrades

Revision ID: 516e504ca564
Revises: add_desired_states_001
Create Date: 2026-04-30 08:45:11.156292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '516e504ca564'
down_revision: Union[str, None] = 'add_desired_states_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('desired_states', 'resource_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('desired_states', 'desired_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('desired_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('desired_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_desired_states_id'), 'desired_states', ['id'], unique=False)
    op.add_column('healing_actions', sa.Column('requires_approval', sa.Boolean(), nullable=False))
    op.add_column('healing_actions', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'healing_actions', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'healing_actions', type_='foreignkey')
    op.drop_column('healing_actions', 'approved_by_id')
    op.drop_column('healing_actions', 'requires_approval')
    op.drop_index(op.f('ix_desired_states_id'), table_name='desired_states')
    op.alter_column('desired_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('desired_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('desired_states', 'desired_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('desired_states', 'resource_id',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###
