"""v2_initial_schema

Revision ID: bc8de533f049
Revises: 
Create Date: 2026-04-16 10:22:19.086719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8de533f049'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_external_id'), 'tenants', ['external_id'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cloud_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scan', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_credentials_id'), 'cloud_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_credentials_tenant_id'), 'cloud_credentials', ['tenant_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=256), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    op.create_index(op.f('ix_event_logs_resource_id'), 'event_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_event_logs_tenant_id'), 'event_logs', ['tenant_id'], unique=False)
    op.create_index('ix_event_logs_tenant_severity', 'event_logs', ['tenant_id', 'severity'], unique=False)
    op.create_index('ix_event_logs_user_created', 'event_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('healing_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=256), nullable=False),
    sa.Column('resource_name', sa.String(length=256), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('auto_triggered', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_healing_idempotency')
    )
    op.create_index(op.f('ix_healing_actions_id'), 'healing_actions', ['id'], unique=False)
    op.create_index('ix_healing_actions_resource', 'healing_actions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_healing_actions_tenant_id'), 'healing_actions', ['tenant_id'], unique=False)
    op.create_index('ix_healing_actions_tenant_status', 'healing_actions', ['tenant_id', 'status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('cloud_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=256), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('network_usage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['cloud_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'credential_id', 'resource_id', name='uq_tenant_cred_resource')
    )
    op.create_index(op.f('ix_cloud_resources_id'), 'cloud_resources', ['id'], unique=False)
    op.create_index('ix_cloud_resources_provider', 'cloud_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_cloud_resources_resource_id'), 'cloud_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_tenant_id'), 'cloud_resources', ['tenant_id'], unique=False)
    op.create_index('ix_cloud_resources_tenant_status', 'cloud_resources', ['tenant_id', 'status'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=256), nullable=False),
    sa.Column('target_id', sa.String(length=256), nullable=False),
    sa.Column('edge_type', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['cloud_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'source_id', 'target_id', 'edge_type', name='uq_graph_edge')
    )
    op.create_index(op.f('ix_graph_edges_id'), 'graph_edges', ['id'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_id'), 'graph_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_id'), 'graph_edges', ['target_id'], unique=False)
    op.create_table('metric_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_history_id'), 'metric_history', ['id'], unique=False)
    op.create_index('ix_metric_history_resource_ts', 'metric_history', ['resource_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_metric_history_timestamp'), 'metric_history', ['timestamp'], unique=False)
    op.create_index('ix_metric_history_type_ts', 'metric_history', ['metric_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_history_type_ts', table_name='metric_history')
    op.drop_index(op.f('ix_metric_history_timestamp'), table_name='metric_history')
    op.drop_index('ix_metric_history_resource_ts', table_name='metric_history')
    op.drop_index(op.f('ix_metric_history_id'), table_name='metric_history')
    op.drop_table('metric_history')
    op.drop_index(op.f('ix_graph_edges_target_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('ix_cloud_resources_tenant_status', table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_tenant_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_resource_id'), table_name='cloud_resources')
    op.drop_index('ix_cloud_resources_provider', table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_id'), table_name='cloud_resources')
    op.drop_table('cloud_resources')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_healing_actions_tenant_status', table_name='healing_actions')
    op.drop_index(op.f('ix_healing_actions_tenant_id'), table_name='healing_actions')
    op.drop_index('ix_healing_actions_resource', table_name='healing_actions')
    op.drop_index(op.f('ix_healing_actions_id'), table_name='healing_actions')
    op.drop_table('healing_actions')
    op.drop_index('ix_event_logs_user_created', table_name='event_logs')
    op.drop_index('ix_event_logs_tenant_severity', table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_tenant_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_resource_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_cloud_credentials_tenant_id'), table_name='cloud_credentials')
    op.drop_index(op.f('ix_cloud_credentials_id'), table_name='cloud_credentials')
    op.drop_table('cloud_credentials')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_external_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
